AAC-546 - Add ASN and NI to defendants search
ministryofjustice/laa-court-data-api pull request #44
Opened 2022-03-23 20:26 UTC by pking-moj

## Description of change

We need the additional search options of NI and ASN on the defendants endpoint to provide feature parity. This adds this in with testing.

## Link to Jira Ticket

- [AAC-546](https://dsdmoj.atlassian.net/browse/AAC-546)

## Screenshots or test evidence if applicable

## Notes

Test data is hard to come by, im not sure if this is working from a CDA/CP point of view. However it is implement as specified

2022-03-24 12:44 UTC, ivanELEC commented
Note that we have a few examples in Last Pass of Dev ASNs and NINOs - I used these to test

2022-03-24 13:14 UTC, ivanELEC commented on laa_court_data_api_app/routers/defendants.py
> +                                        params={"filter[national_insurance_number]": nino})
Logs are a little bit misleading as they all indicate Get_Urn even though we are getting via ASN

2022-03-24 13:15 UTC, pking-moj commented on postman/collections/defendants.postman_collection.json
> +					]
Fixed

2022-03-24 13:19 UTC, ivanELEC approved these changes

2022-03-24 14:07 UTC, Obsiye approved these changes

2022-03-24 14:30 UTC, mabely requested changes

2022-03-24 14:30 UTC, mabely commented on laa_court_data_api_app/routers/defendants.py
> +        logging.info(f"Defendants_Get_asn_{asn}")
I'ma be really annoying and ask that 'asn' and 'nino' be pascal case just for predictability when searching through logs

2022-03-25 09:15 UTC, mabely approved these changes

2022-03-25 09:24 UTC, ivanELEC approved these changes

2022-03-25 09:30 UTC, Obsiye approved these changes

2022-03-25 09:43 UTC, merged